### ISSUE TITLE
Deprecated API warning ("file parameter")

### ISSUE THREAD

**Issue by sondreb** [sondreb/action-release#1]
Logged when running this action now, needs to be updated:

```
Deprecation: [@octokit/rest] "file" parameter is deprecated for ".repos.uploadReleaseAsset()". Use "data" instead
    at d:\a\_actions\sondreb\action-release\master\node_modules\@octokit\plugin-rest-endpoint-methods\dist-node\index.js:13145:26
    at Array.forEach (<anonymous>)
    at Object.patchedMethod [as uploadReleaseAsset] (d:\a\_actions\sondreb\action-release\master\node_modules\@octokit\plugin-rest-endpoint-methods\dist-node\index.js:13142:26)
    at upload (d:\a\_actions\sondreb\action-release\master\action.js:171:48)
    at d:\a\_actions\sondreb\action-release\master\action.js:192:15
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'Deprecation'
```

**Comment by sondreb** [comment]
This was fixed previously.
